# Generated by Django 4.2.1 on 2023-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathermeasure',
            name='id',
        ),
        migrations.AlterField(
            model_name='weathermeasure',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weathermeasure',
            name='pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weathermeasure',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weathermeasure',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
